version: '3.8'
services:

    
    influxdb:
        image: influxdb:1.8
        container_name: influxdb
        ports:
        - "8086:8086"
        networks:
        - k6-net

    grafana:
        image: grafana/grafana
        container_name: grafana
        ports:
        - "3000:3000"
        environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin
        networks:
        - k6-net

networks:
    k6-net:
        driver: bridge